robots_config:
  nb_robots: 1
  robot_ids: ["robot_1"]
  robot_1:
    info:
      name: "pr2"
      arm_group: "left_arm"
      eef: "left_gripper"
      eef_frame: "l_gripper_tool_frame"
      world_frame: "odom_combined"
      arm_home_pose: "home"
      eef_open_pose: "open"
      eef_close_pose: "close"
      max_gripper_width: 0.1
      grasp_frame_transform: [0, 0, 0, 0, 0, 0]
      approach_retreat_direction: [1, 0, 0]
    base_pose: [0, 0, 0, 0, 0, 0]

# robots_config:
#   nb_robots: 1
#   robot_ids: ["robot_1"]
#   robot_1:
#     info:
#       name: "pr2"
#       arm_group: "right_arm"
#       eef: "right_gripper"
#       eef_frame: "r_gripper_tool_frame"
#       world_frame: "odom_combined"
#       arm_home_pose: "home"
#       eef_open_pose: "open"
#       eef_close_pose: "close"
#       max_gripper_width: 0.1
#       grasp_frame_transform: [0, 0, 0, 0, 0, 0]
#       approach_retreat_direction: [1, 0, 0]
#     base_pose: [0, 0, 0, 0, 0, 0]