l_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
  gains:
    l_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_upper_arm_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_elbow_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_forearm_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_wrist_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

r_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
  gains:
    r_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_upper_arm_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_elbow_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_forearm_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_wrist_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1


head_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_pan_joint
    - head_tilt_joint
  gains:
    head_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    head_tilt_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - torso_lift_joint
  gains:
    torso_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1


r_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_gripper_l_finger_joint
    - r_gripper_motor_slider_joint
    - r_gripper_motor_screw_joint
    - r_gripper_joint
  gains:
    r_gripper_l_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_gripper_motor_slider_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_gripper_motor_screw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
l_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_gripper_l_finger_joint
    - l_gripper_motor_slider_joint
    - l_gripper_motor_screw_joint
    - l_gripper_joint
  gains:
    l_gripper_l_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_gripper_motor_slider_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_gripper_motor_screw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1